# Generated by Django 4.2.1 on 2023-05-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombrehijo', models.CharField(max_length=50)),
                ('ruthijo', models.CharField(max_length=12)),
                ('fecha', models.DateField()),
                ('horas_reserva', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
