# Generated by Django 4.2.1 on 2023-05-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nombrehijo',
            field=models.CharField(max_length=25),
        ),
    ]
